/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_ganaderia;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelos.Animal;
import modelos.AnimalJpaController;
import modelos.Enfermedad;
import modelos.EnfermedadJpaController;
import modelos.Historialenf;
import modelos.HistorialenfJpaController;
import modelos.Parcela;
import modelos.ParcelaJpaController;

/**
 *
 * @author jvifdz-GRANDE
 */
public class FormAsignarEnfermedad extends javax.swing.JDialog {

    /**
     * Creates new form FormAsignarEnfermedad
     */
    public Animal[] animal;
    AnimalJpaController controladorAnimal = new AnimalJpaController();
    List<Enfermedad> listaEnfermedad = new ArrayList<>();
    String[] columnasEnfermedad = {"Nombre"};

    DefaultTableModel modeloEnfermedad = new DefaultTableModel(columnasEnfermedad, 0);
    public Enfermedad enfermedad;

    EnfermedadJpaController controladorEnfermedad = new EnfermedadJpaController();

    HistorialenfJpaController controladorHistorial = new HistorialenfJpaController();

    boolean creado = false;

    public FormAsignarEnfermedad(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public FormAsignarEnfermedad(java.awt.Frame parent, boolean modal, Animal[] animal,java.util.Date fechaMaxima) {
        super(parent, modal);
        initComponents();
        this.animal = animal;
        getTablaTotalEnfermedad();
        this.setLocationRelativeTo(null);
        this.jTableEnfermedad.setDefaultEditor(Object.class, null);
        this.jDateAsignarEnfermedad.setMaxSelectableDate(fechaMaxima);
        this.setResizable(false);
        this.jDateAsignarEnfermedad.setDate(fechaMaxima);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEnfermedad = new javax.swing.JTable();
        TxBuscar = new javax.swing.JTextField();
        BtBuscar = new javax.swing.JButton();
        BtConfirmar = new javax.swing.JButton();
        BtCancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jDateAsignarEnfermedad = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Asignar Enfermedad");

        jTableEnfermedad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableEnfermedad);

        BtBuscar.setText("Buscar");
        BtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtBuscarActionPerformed(evt);
            }
        });

        BtConfirmar.setText("Confirmar");
        BtConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtConfirmarActionPerformed(evt);
            }
        });

        BtCancelar.setText("Cancelar");
        BtCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCancelarActionPerformed(evt);
            }
        });

        jLabel2.setText("Fecha");

        jLabel3.setText("Buscador");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TxBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateAsignarEnfermedad, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addComponent(BtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91))))
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(BtConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jDateAsignarEnfermedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TxBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtConfirmar)
                    .addComponent(BtCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtConfirmarActionPerformed
        // TODO add your handling code here:
        
        if(this.jTableEnfermedad.getSelectedRow()==-1){
            JOptionPane.showMessageDialog(null, "Seleccione una enfermedad", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        Date date;
        if (this.jDateAsignarEnfermedad.getDate()==null) {
            date = new Date();
        }else{
        date=jDateAsignarEnfermedad.getDate();
        }
        

        enfermedad = this.listaEnfermedad.get(this.jTableEnfermedad.getSelectedRow());
        
        for (int i = 0; i < this.animal.length; i++) {
            Historialenf historial = new Historialenf();
            historial.setFkAnimal(animal[i]);
            historial.setFechaEnfermedad(date);
            historial.setFkEnfermedad(enfermedad);
            controladorHistorial.create(historial);
            animal[i].getHistorialenfList().add(historial);
        }
        creado = true;
        this.dispose();


    }//GEN-LAST:event_BtConfirmarActionPerformed

    private void BtCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_BtCancelarActionPerformed

    private void BtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtBuscarActionPerformed
        // TODO add your handling code here:
        modeloEnfermedad.setRowCount(0);
        listaEnfermedad.clear();
        List <Enfermedad> lista;
        EnfermedadJpaController enfermedadController = new EnfermedadJpaController();
        try {
            lista = enfermedadController.EnfermedadNombre(TxBuscar.getText());
            //lista = controlador.findAnimalEntities();
            for (int i = 0; i < lista.size(); i++) {
                
                EnfermedadAModelo(lista.get(i));
            }
            this.jTableEnfermedad.setFocusable(false);
            this.jTableEnfermedad.setModel(modeloEnfermedad);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar los datos: " + e.toString());
        }
    }//GEN-LAST:event_BtBuscarActionPerformed

    

    private void getTablaTotalEnfermedad() {
        listaEnfermedad.clear();
        List lista;

        try {
            lista = controladorEnfermedad.findEnfermedadEntities();
            //lista = controlador.findAnimalEntities();
            for (int i = 0; i < lista.size(); i++) {
                enfermedad = (Enfermedad) lista.get(i);
                EnfermedadAModelo(enfermedad);
            }
            this.jTableEnfermedad.setFocusable(false);
            this.jTableEnfermedad.setModel(modeloEnfermedad);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar los datos: " + e.toString());
        }

    }

    public void EnfermedadAModelo(Enfermedad enfermedad) {
        Object[] objeto = new Object[1];
        objeto[0] = enfermedad.getNombre();
        modeloEnfermedad.addRow(objeto);
        listaEnfermedad.add(enfermedad);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAsignarEnfermedad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAsignarEnfermedad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAsignarEnfermedad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAsignarEnfermedad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormAsignarEnfermedad dialog = new FormAsignarEnfermedad(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtBuscar;
    private javax.swing.JButton BtCancelar;
    private javax.swing.JButton BtConfirmar;
    private javax.swing.JTextField TxBuscar;
    private com.toedter.calendar.JDateChooser jDateAsignarEnfermedad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableEnfermedad;
    // End of variables declaration//GEN-END:variables
}
