/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_ganaderia;

import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import modelos.Cliente;
import modelos.Factura;
import modelos.FacturaJpaController;

/**
 *
 * @author jvifdz-GRANDE
 */
public class FormEditarCliente extends javax.swing.JDialog {

    /**
     * Creates new form FormEditarCliente
     */
    boolean creado = false;
    public Cliente cliente;
    Factura factura;
    List<Factura> listaFactura = new ArrayList<>();
    String[] columnasFactura = {"Número factura", "Precio", "IVA", "Fecha venta", "Ganaderia emisora"};
    DefaultTableModel modeloFactura = new DefaultTableModel(columnasFactura, 0);
    
    
    public FormEditarCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    public FormEditarCliente(java.awt.Frame parent, boolean modal,Cliente cliente) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Clientes");
        this.Confirmar.setText("Editar");
        this.setLocationRelativeTo(null);
        this.cliente=cliente;
        this.TxNombre.setText(cliente.getNombre());
        this.TxDni.setText(cliente.getDni());
        this.TxCodExplotacion.setText(cliente.getCodExplotacion());
        this.TxCodPostal.setText(cliente.getCodPostal().toString());
        this.TxNumeroTelf.setText(cliente.getTelefono().toString());
        this.TxDireccion.setText(cliente.getDireccion());
        this.TxCorreo.setText(cliente.getCorreo());
        this.setResizable(false);
        getTablaTotalFactura();
        this.jTableFacturaClientes.setDefaultEditor(Object.class, null);
        this.LblFacturaCliente.setText("Facturas del cliente "+this.cliente.getNombre());
        
        this.jTableFacturaClientes.addMouseListener(new MouseAdapter() {
            public void mousePressed(MouseEvent mouseEvent) {
                JTable table = (JTable) mouseEvent.getSource();

                if (mouseEvent.getClickCount() == 2 && table.getSelectedRow() != -1) {
                    // your valueChanged overridden method 

                    // your valueChanged overridden method 
                    factura = listaFactura.get(jTableFacturaClientes.getSelectedRow());

                    FormDetalleFactura formParcela = new FormDetalleFactura(new Formulario(), true, factura);
                    formParcela.setVisible(true);

                }
            }
        });
    }
    
    
    
    private void getTablaTotalFactura() {
        listaFactura.clear();
        List<Factura> lista;
        FacturaJpaController controlador = new FacturaJpaController();
        try {
            lista = controlador.FacturasCliente(this.cliente.getNombre());
            //lista = controlador.findAnimalEntities();
            for (int i = 0; i < lista.size(); i++) {

                FacturaAModelo(lista.get(i));
            }
            this.jTableFacturaClientes.setFocusable(false);
            this.jTableFacturaClientes.setModel(modeloFactura);
            this.LblTotal.setText("Total " + this.jTableFacturaClientes.getRowCount());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar los datos: " + e.toString());
        }

    }
    public void FacturaAModelo(Factura factura) {
        Object[] objeto = new Object[5];
        objeto[0] = factura.getIdFactura();
        objeto[1] = factura.getPrecioTotal();
        objeto[2] = factura.getIva();
        objeto[3] = new SimpleDateFormat("dd MMM yyyy").format(new Date(factura.getFechaVenta().getTime()));
        objeto[4] = factura.getFkdatosNegocio().getNombre();
        modeloFactura.addRow(objeto);
        listaFactura.add(factura);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        Confirmar = new javax.swing.JButton();
        TxDireccion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        TxCorreo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFacturaClientes = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TxNumeroTelf = new javax.swing.JFormattedTextField();
        TxDni = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TxNombre = new javax.swing.JTextField();
        TxCodPostal = new javax.swing.JFormattedTextField();
        Cancelar = new javax.swing.JButton();
        TxCodExplotacion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        LblTotal = new javax.swing.JLabel();
        LblFacturaCliente = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel7.setText("Dirección");

        Confirmar.setText("Confirmar");
        Confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmarActionPerformed(evt);
            }
        });

        jLabel4.setText("Numero de explotación");

        jLabel1.setText("Editar cliente");

        jTableFacturaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableFacturaClientes);

        jLabel5.setText("Código postal");

        jLabel8.setText("Correo");

        TxNumeroTelf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#########"))));

        jLabel2.setText("Nombre");

        jLabel6.setText("Número de telefono");

        TxCodPostal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#####"))));

        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });

        jLabel3.setText("DNI/NIF");

        LblTotal.setText("jLabel9");

        LblFacturaCliente.setText("Facturas del cliente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(TxNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                            .addComponent(TxCodExplotacion, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TxNumeroTelf, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(38, 38, 38)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(TxDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                            .addComponent(TxDni)
                                            .addComponent(TxCodPostal)))
                                    .addComponent(TxCorreo)))
                            .addComponent(LblFacturaCliente)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(46, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Confirmar)
                        .addGap(127, 127, 127)
                        .addComponent(Cancelar)
                        .addGap(146, 146, 146))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(LblTotal)
                        .addGap(91, 91, 91))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TxNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(TxDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxCodExplotacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(TxCodPostal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TxNumeroTelf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(TxDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(TxCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(LblFacturaCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblTotal)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Confirmar)
                    .addComponent(Cancelar))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmarActionPerformed
        // TODO add your handling code here:
        if(this.TxNombre.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Introduzca el nombre del cliente", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(this.TxDni.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Introduzca el dni del cliente", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(this.TxCodExplotacion.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Introduzca el código de explotacion del cliente", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(this.TxCodPostal.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Introduzca el código postal del cliente", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(this.TxNumeroTelf.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Introduzca el número de teléfono del cliente", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(this.TxDireccion.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Introduzca la dirección del cliente", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(this.TxCorreo.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Introduzca el correo del cliente", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        

        String nombre = this.TxNombre.getText();
        String DNI = this.TxDni.getText();
        String codExplotacion = this.TxCodExplotacion.getText();
        int codPostal = Integer.parseInt(this.TxCodPostal.getText());
        int numTelf = Integer.parseInt(this.TxNumeroTelf.getText());
        String direccion = this.TxDireccion.getText();
        String correo = this.TxCorreo.getText();

        cliente.setNombre(nombre);
        cliente.setDni(DNI);
        cliente.setCodExplotacion(codExplotacion);
        cliente.setCodPostal(codPostal);
        cliente.setDireccion(direccion);
        cliente.setTelefono(numTelf);
        cliente.setCorreo(correo);
        
        creado = true;
        this.dispose();
        
    }//GEN-LAST:event_ConfirmarActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_CancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormEditarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormEditarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormEditarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormEditarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormEditarCliente dialog = new FormEditarCliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar;
    private javax.swing.JButton Confirmar;
    private javax.swing.JLabel LblFacturaCliente;
    private javax.swing.JLabel LblTotal;
    private javax.swing.JTextField TxCodExplotacion;
    private javax.swing.JFormattedTextField TxCodPostal;
    private javax.swing.JTextField TxCorreo;
    private javax.swing.JTextField TxDireccion;
    private javax.swing.JTextField TxDni;
    private javax.swing.JTextField TxNombre;
    private javax.swing.JFormattedTextField TxNumeroTelf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableFacturaClientes;
    // End of variables declaration//GEN-END:variables
}
