/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_ganaderia;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelos.Animal;
import modelos.AnimalJpaController;
import modelos.Historialparcela;
import modelos.HistorialparcelaJpaController;
import modelos.Parcela;
import modelos.ParcelaJpaController;

/**
 *
 * @author jvifdz-GRANDE
 */
public class FormAsignarParcela extends javax.swing.JDialog {

    /**
     * Creates new form FormAsignarParcela
     */
    public Animal[] animal;
    AnimalJpaController controladorAnimal = new AnimalJpaController();
    Parcela parcela;
    List<Parcela> listaParcela = new ArrayList<>();
    String[] columnasParcela = {"Nombre", "Tamaño", "Lugar Situada"};
    DefaultTableModel modeloParcela = new DefaultTableModel(columnasParcela, 0);
    ParcelaJpaController parcelaController = new ParcelaJpaController();
    HistorialparcelaJpaController historialController = new HistorialparcelaJpaController();

    boolean creado = false;

    private void getTablaTotalParcela() {
        listaParcela.clear();
        List lista;
        ParcelaJpaController controlador = new ParcelaJpaController();
        try {
            lista = controlador.findParcelaEntities();
            //lista = controlador.findAnimalEntities();
            for (int i = 0; i < lista.size(); i++) {
                parcela = (Parcela) lista.get(i);
                ParcelaAModelo(parcela);
            }
            this.jTableParcela.setFocusable(false);
            this.jTableParcela.setModel(modeloParcela);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar los datos: " + e.toString());
        }

    }

    public void ParcelaAModelo(Parcela parcela) {
        Object[] objeto = new Object[3];
        objeto[0] = parcela.getNombre();
        objeto[1] = parcela.getTamano();
        objeto[2] = parcela.getLugarSituada();
        modeloParcela.addRow(objeto);
        listaParcela.add(parcela);
    }

    public FormAsignarParcela(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setResizable(false);

    }

    public FormAsignarParcela(java.awt.Frame parent, boolean modal, Animal[] animal) {
        super(parent, modal);
        this.animal = animal;
        initComponents();
        getTablaTotalParcela();
        this.jTableParcela.setDefaultEditor(Object.class, null);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.jDateFechaEntrada.setDate(new Date());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BtConfirmar = new javax.swing.JButton();
        BtCancelar = new javax.swing.JButton();
        TxBusquedaParcela = new javax.swing.JTextField();
        BtBuscarParcela = new javax.swing.JButton();
        jDateFechaEntrada = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableParcela = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Asignar parcela");

        BtConfirmar.setText("Confirmar");
        BtConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtConfirmarActionPerformed(evt);
            }
        });

        BtCancelar.setText("Cancelar");
        BtCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCancelarActionPerformed(evt);
            }
        });

        BtBuscarParcela.setText("Buscar");
        BtBuscarParcela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtBuscarParcelaActionPerformed(evt);
            }
        });

        jTableParcela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableParcela);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TxBusquedaParcela, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateFechaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addComponent(BtBuscarParcela))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(jLabel1)))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addComponent(jDateFechaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxBusquedaParcela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtBuscarParcela))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtConfirmar)
                    .addComponent(BtCancelar))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtBuscarParcelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtBuscarParcelaActionPerformed
        // TODO add your handling code here:

        modeloParcela.setRowCount(0);
        List lista;
        ParcelaJpaController parcelaController = new ParcelaJpaController();
        try {
            lista = parcelaController.ParcelasNombre(TxBusquedaParcela.getText());
            //lista = controlador.findAnimalEntities();
            for (int i = 0; i < lista.size(); i++) {
                parcela = (Parcela) lista.get(i);
                ParcelaAModelo(parcela);
            }
            this.jTableParcela.setFocusable(false);
            this.jTableParcela.setModel(modeloParcela);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar los datos: " + e.toString());
        }

    }//GEN-LAST:event_BtBuscarParcelaActionPerformed

    private void BtConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtConfirmarActionPerformed
        // TODO add your handling code here:

        if(this.jTableParcela.getSelectedRow()==-1){
            JOptionPane.showMessageDialog(null, "Seleccione una parcela", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        
        Date fechaEntrada;
        if (this.jDateFechaEntrada.getDate() == null) {
            fechaEntrada = new Date();
        } else {
            fechaEntrada = jDateFechaEntrada.getDate();
        }

        parcela = this.listaParcela.get(this.jTableParcela.getSelectedRow());

        for (int i = 0; i < this.animal.length; i++) {
            int numeroParcela = animal[i].getHistorialparcelaList().size() - 1;
            try {
                if (animal[i].getHistorialparcelaList().isEmpty()) {

                    crearHistorialParcela(animal[i], parcela, fechaEntrada);

                } else {

                    animal[i].getHistorialparcelaList().get(numeroParcela).setFechaSalida(fechaEntrada);
                    historialController.edit(animal[i].getHistorialparcelaList().get(numeroParcela));

                    crearHistorialParcela(animal[i], parcela, fechaEntrada);
                }

            } catch (Exception ex) {
                Logger.getLogger(FormAsignarParcela.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        creado = true;
        this.dispose();

    }//GEN-LAST:event_BtConfirmarActionPerformed

    private void BtCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_BtCancelarActionPerformed

    private void crearHistorialParcela(Animal animal, Parcela parcela, Date fechaEntrada) {

        Historialparcela historial = new Historialparcela();
        historial.setFkAnimal(animal);
        historial.setFkParcela(parcela);
        historial.setFechaEntrada(fechaEntrada);
        historial.setFechaSalida(null);
        historialController.create(historial);
        animal.getHistorialparcelaList().add(historial);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAsignarParcela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAsignarParcela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAsignarParcela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAsignarParcela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormAsignarParcela dialog = new FormAsignarParcela(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtBuscarParcela;
    private javax.swing.JButton BtCancelar;
    private javax.swing.JButton BtConfirmar;
    private javax.swing.JTextField TxBusquedaParcela;
    private com.toedter.calendar.JDateChooser jDateFechaEntrada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableParcela;
    // End of variables declaration//GEN-END:variables
}
